# Generated by Django 5.1.4 on 2024-12-21 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('location_type', models.CharField(max_length=100)),
                ('employment_type', models.CharField(max_length=100)),
                ('skills', models.TextField()),
                ('compensation', models.CharField(max_length=100)),
                ('job_details', models.TextField()),
                ('posted_date', models.DateField()),
                ('updated_date', models.DateField()),
            ],
        ),
    ]
